apiVersion: apps/v1
kind: Deployment
metadata:
  name: htx-assignment-deployment
  labels:
    app: htx-assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: htx-assignment
  template:
    metadata:
      labels:
        app: htx-assignment
    spec:
      containers:
      - name: htx-assignment
        image: zlightningzap/htx-assignment:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: htx-assignment-config
              key: message
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: htx-assignment-secret
              key: api_key
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---