apiVersion: v1
kind: Service
metadata:
  name: htx-assignment-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: htx-assignment