name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: HTXApp/Dockerfile
        push: true
        tags: zlightningzap/htx-assignment:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Install kubectl
      run: |
        curl -LO "https://amazon-eks.s3.us-west-2.amazonaws.com/$(curl -s https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.11/launch-templates/eksctl-1.20.11-linux-amd64.tar.gz | grep -oP '\d+\.\d+\.\d+' | head -n 1)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin

    - name: Update kubeconfig
      run: |
        aws eks --region ap-southeast-1 update-kubeconfig --name HTXAssignment

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
